# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{genmachine}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Wecker"]
  s.date = %q{2011-08-18}
  s.default_executable = %q{genmachine}
  s.description = %q{Takes a state table where the following are defined: state, input+conditions, accumulate-action, pre-transition-actions, and transition-to. It takes that state table and generates very fast parsers. Similar to Ragel. Currently only outputs pure Ruby.}
  s.email = %q{joseph.wecker@gmail.com}
  s.executables = ["genmachine"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/genmachine",
    "genmachine.gemspec",
    "lib/VERSION",
    "lib/genmachine.rb",
    "lib/genmachine/char_set.rb",
    "lib/genmachine/generator.rb",
    "lib/genmachine/generators/helpers/general.rb",
    "lib/genmachine/generators/helpers/ruby.rb",
    "lib/genmachine/generators/ruby.rb",
    "lib/genmachine/generators/templates/ruby/executable.erb",
    "lib/genmachine/generators/templates/ruby/lib.erb.rb",
    "lib/genmachine/spec_parser.rb",
    "machines/genmachine.machine",
    "misc/genmachine.vim",
    "test/helper.rb",
    "test/test_genmachine.rb"
  ]
  s.homepage = %q{http://github.com/josephwecker/genmachine}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Generates parsers based on a fancy state-table}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

